config/routes.rb
Rails.application.routes.draw do
  get 'u/:id/', to: "users#profile", as: :user
  get 'search', to: "search#index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # /posts/1/comments/4
  
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.ransack(params[:q])
    @posts = @query.result(distinct: true) # distinct - unique data
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class: "d-flex") do |f| %>
    <%= f.search_field :title_or_content_or_introduction_i_cont_any, placeholder:"Enter your query..." %>
    <%= f.submit %>
<%end%>

app/views/search/index.html.erb
<h1><%=pluralize(@posts.count, "Result")%></h1>

<table class="table table-borderless table-hover">
  <thead>
    <tr>
      <th><%= sort_link(@query, :title, "Title", default_order: :desc) %></th>
      <th><%= sort_link(@query, :content, "Content") %></th>
      <th><%= sort_link(@query, :introduction, "Introduction") %></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%=  post.content.body.to_plain_text.truncate(25) %></td>
        <td><%=  post.introduction%></td>
        <td><%= link_to post.user.username, user_path(post.user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>