config/routes.rb
Rails.application.routes.draw do
  get 'u/:id/', to: "users#profile", as: :user
  get 'search', to: "search#index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # /posts/1/comments/4
  
  resources :posts do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :comments, dependent: :destroy
    has_rich_text :content

    def self.ransackable_attributes(auth_object = nil)
        ["title", "content", "introduction"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["title", "content", "introduction"]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create

    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :introduction, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="d-flex justify-content-center">
  <div class="card px-4", style="width:60rem">
    <div class="mt-3">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title,  class: "form-control mb-3"%>
    </div>

    <div>
      <%= form.label :content, style: "display: block" %>
      <%= form.rich_text_area :content, placeholder: "Enter body of post", class: "form-control"%>
    </div>

    <div>
      <%= form.label :introduction, style: "display: block" %>
      <%= form.text_area :introduction, class: "form-control mb-3"%>
    </div>

    <div>
      <%= form.label :image, style: "display: block" %>
      <%= form.file_field :image, class: "form-control mb-3"%>
    </div>

    <div class="mb-4">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  </div>
</div>


<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>


  <div class="justify-content-center row row-cols-3 ">
    <% @posts.each do |post| %>
      <div class="index-card card col-3 ms-5 mb-3">
        <% if post.image.attached?%>
            <%= image_tag(post.image, class:"post_image card-img-top")%>
        <%end%>
        <div class="card-body">
          <h5 class="card-title">
              <%= link_to post.title, post_path(post)%>
          </h5>

          <p class="card-text">
            <%= truncate(post.introduction, length:100) %>
          </p>
        </div>

      </div>
    <% end %>
  </div>
<%= link_to "New post", new_post_path %>

<%= button_to "Sign out", destroy_user_session_path, method: :delete %>

<%# для каждого поста надо добавить introduction, который будет писаться в форме при создании самого поста%> 
<%# для кажд.отдельного intro из паршла post добавлять bootstrap стили %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="header d-flex align-items-center">
  <div class="flex-shrink-0 col-4">
    <% if @post.image.attached?%>
      <%= image_tag(@post.image, class:"intro-image")%>
    <%end%>
  </div>
  <div class="article-header-content col-8">
    <h2>
      <%= @post.title%>
    </h2>

    <p>
      <%= @post.introduction%>
    </p>
  </div>
</div>


<br>


<div class="content-text">
  <%= @post.content%>
</div>  




<div>

  <h5>Comments:<%= @post.comments.count%></h5>

  <%= render "active_storage/comments/form", post: @post%>

  <% @post.comments.each do |comment|%>

    <%= render "active_storage/comments/comment", post: @post, comment: comment%>

  <%end%>

</div>




<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>